version: 2.1

orbs:
  mattermost-notify: bulletlogic/mattermost-notify@0.0.4

jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/gusta-api
    steps:
      - checkout
      - run: docker-compose up -d --build
      - run: docker-compose exec api npm run migrate
      - run:
          command: |
            mkdir -p coverage/
            docker-compose run --rm -v "$PWD/coverage:/coverage" api npm test
            bash <(curl -s https://codecov.io/bash) -f "./coverage/lcov.info"
  notify_success:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - mattermost-notify/notify_on_success:
          webhook: '$MATTERMOST_WEBHOOK_API'
  notify_failure:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - mattermost-notify/notify_on_failure:
          webhook: '$MATTERMOST_WEBHOOK_API'

workflows:
  version: 2
  main_workflow:
    jobs:
      - build:
          context: builds
      - notify_success:
          context: webhooks
          requires:
            - build
      - notify_failure:
          context: webhooks
          requires:
            - build
